### ISSUE TITLE
Numeric less than or equal op begins quoting construct

### ISSUE THREAD

**Issue by 0racle** [vim-perl/vim-perl6#1] opened 2016-09-08 12:52 UTC
# Description of issue

When using the `Numeric less than or equal to` operator, the `<` causes the syntax highlighter to start a `<>` quoting construct until it sees a `>`.
# Screenshot of the issue:

![Screenshot](http://www.0racle.info/images/vim_perl6_quote.png)

Above screenshot taken using the 256-color [jellybeans](https://github.com/nanotech/jellybeans.vim) color scheme.
# Sample code:

``` perl6
if 3 <= 4 {
    say "It now thinks we are inside a '<>' quoting construct";
}

# And will continue to do so until > appears;

if 4 >= 3 { 
    say "No such problem here";
}
```
# Link to vimrc

[vimrc](https://gist.github.com/0racle/c82a1cae179e8f27d5e13eca2b4c8b3f)
# Output of `vim --version`

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 21 2015 12:30:04)
Included patches: 1-712
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-i386-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions   
```

**Comment by hoelzro** [comment] 2016-09-08 15:21
@0racle Thanks for the report!  Which version of the vim-perl6 files are you using?  I'm not seeing this on my setup.

**Comment by 0racle** [comment] 2016-09-09 07:06
I'm on the same commit. I've also tried on another box (one Ubuntu, one Centos, both Vim7.4) and it is also exhibiting the same issue.

**Comment by 0racle** [comment] 2016-09-12 06:26
I used `git bisect` and found that [ab2351f](https://github.com/vim-perl/vim-perl6/commit/ab2351f8bc2d98013bd0feff06bee3136cc43bd8) is when this issue started for me.

I'll try to narrow it down further to the offending line(s)

**Comment by hoelzro** [comment] 2016-09-12 16:12
@0racle Does this happen with no vimrc loaded? Ex. `vim -u NONE -c 'source syntax/perl6.vim' -c 'syntax on' -c 'setf perl6' example.pl`

I tried this after building Vim 7.4 from patch 712 (`git checkout v7.4.712 && ./configure --with-features=huge && make install`), and am still unable to reproduce the problem.

**Comment by 0racle** [comment] 2016-09-13 07:27
If I do the following...
`vim -u NONE -c 'source syntax/perl6.vim' -c 'syntax on' -c 'setf perl6' example.pl`

I don't see an issue... ***but*** it looks identical if I do this
`vim -u NONE -c 'syntax on' -c 'setf perl6' example.pl`

which suggests the syntax file is not being sourced correctly.

However, if I copy `syntax/perl6.vim` to `~.vim/syntax` and then do the 2nd command, then I do see the issue.

Interestingly, if I delete the `perl.vim` and `perl6.vim` files from vim's default runtime folder (`/usr/share/vim/.../syntax`) and then run the first line, I get no syntax highlighting... further providing support that sourcing the the syntax file via the cmdline doesn't work (at least on my machine).

I will clone the vim repo and build the same version as you (on Ubuntu and Centos) and do some more testing.

**Comment by hoelzro** [comment] 2016-09-13 14:09
@0racle Ok, that's leading me to believe that your Vim is using an out-of-date `perl6.vim` file.  The first command (with `source syntax/perl6.vim`) makes sure that only our `perl6.vim` is loaded.  If you try `vim -u NONE -c 'syntax on' -c 'setf perl6' example.pl`, run `:scriptnames` in the vim instance that comes up.  You should see an entry for `syntax/perl6.vim`, which is the syntax file your vim is using.  If this is not the one you intend, you either don't have `&runtimepath` set up correctly, or our `syntax/perl6.vim` isn't on your runtimepath.

**Comment by zostay** [comment] 2017-06-01 03:31
I am seeing this problem using the latest commit here forked into my dotfiles: ccef6a3bab83b20c94f0d4c32ef028bff1cc6c4d

The attached screenshots show the problem both in vim and neovim (running reasonably recent builds of each o macOS. This was running each with `vim -u NONE -c 'syntax on' -c 'setf perl6' example.pl` where `example.pl` is a module I'm porting. I ran `:source syntax/perl6.vim` in each and then captured the output of `:scriptnames`. 

Here's neovim:

<img width="549" alt="screen shot 2017-05-31 at 22 25 57" src="https://cloud.githubusercontent.com/assets/34711/26663495/a52e1eca-4650-11e7-8a9f-66ae2fab63cd.png">

And here's vim:

<img width="520" alt="screen shot 2017-05-31 at 22 26 55" src="https://cloud.githubusercontent.com/assets/34711/26663500/b12be40a-4650-11e7-9eff-63dd5e740086.png">

**Comment by zostay** [comment] 2017-06-01 17:57
I can confirm that the reversion @0racle found via bisect does fix the problem with the mentioned regression.

**Comment by 0racle** [comment] 2017-08-25 11:42
Here's an [asciinema](https://asciinema.org/a/2b6zg2p2xj8qgs94i57z8hc1j) from my system showing the issue with no vimrc.

This issue was also called out by Evan Miller in his recent [Review of Perl6](http://www.evanmiller.org/a-review-of-perl-6.html)

Referring the line I mentioned above from commit [ab2351f](https://github.com/vim-perl/vim-perl6/commit/ab2351f8bc2d98013bd0feff06bee3136cc43bd8), making the suggested change (adding 2 characters) does not appear to cause a regression with the issue that commit sought to solve (ie. `Fix highlighting of <-a -b -c>`).

The regression it cause with regards to `if < a b c > ... ` is, I think, a more acceptable corner case, as it is not likely to be a common expression. Importantly, `for < a b c > ...` is unaffected by this change and highlights properly.

Given that the issue has been confirmed on multiple systems, and the high visibility of the issue due to Evan's review, I have created a [pull request](https://github.com/vim-perl/vim-perl6/pull/7) to merge this change.

**Comment by hoelzro** [comment] 2017-08-31 03:16
Thanks for the fix @0racle - I just merged your PR!

**Closed** 2017-08-31 03:16 UTC
